// Code generated by goctl. DO NOT EDIT.
package types

type ConfigInfo struct {
	Addr    string `json:"addr"`
	Inspect bool   `json:"inspect"`
}

type StartTunnelReq struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	LocalIP    string `json:"local_ip"`
	LocalPort  int    `json:"local_port"`
	RemotePort int    `json:"remote_port"`
}

type StartTunnelResp struct {
	Name      string     `json:"name"`       //
	URI       string     `json:"uri"`        // /api/tunnels
	PublicUrl string     `json:"public_url"` // tcp://****.3232
	Proto     string     `json:"proto"`      // tcp
	Config    ConfigInfo `json:"config"`     //
}

type StopTunnelResp struct {
	ErrCode string `json:"errcode"`
	ErrTxt  string `json:"errtxt"`
	Respond string `json:"respond"`
}

type GetTunnelDetailReq struct {
	Name string `path:"name"`
}

type GetTunnelDetialResp struct {
	Token        string `json:"token"`
	AccessExpire string `json:"accessExpire"`
	RefreshAfter string `json:"refreshAfter"`
}

type ListCaptureRequestResp struct {
	ErrCode string     `json:"errcode"`
	ErrTxt  string     `json:"errtxt"`
	Respond ConfigInfo `json:"respond"`
}
