// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	frpgoadmin "frpgo/api/internal/handler/frpgo/admin"
	frpgotest "frpgo/api/internal/handler/frpgo/test"
	"frpgo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: frpgotest.FrpgoPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tunnels",
				Handler: frpgoadmin.StartTunnelHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tunnels/:name",
				Handler: frpgoadmin.StopTunnelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tunnels/:name",
				Handler: frpgoadmin.GetTunnelDetialHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/requests/http/:limit/:tunnel_name",
				Handler: frpgoadmin.ListCapturedRequestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
